apiVersion: v1
kind: PersistentVolume
metadata:
  name: tlsperf-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/tlsperf-data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tlsperf-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---


apiVersion: v1
kind: Pod
metadata:
  name: tlsperf-web
  labels:
    app: tlsperf-web
spec:
  volumes:
    - name: tlsperf-pv-storage
      persistentVolumeClaim:
        claimName: tlsperf-pv-claim
  serviceAccountName: tlsperf-admin
  containers:
    - name: tlsperf-db
      image: tlspack/tlsperf:latest
      imagePullPolicy: Always
      command: ["mongod"]
      args: ["--noauth", "--dbpath", "/data"]
      volumeMounts:
        - name: tlsperf-pv-storage
          mountPath: "/data"
    - name: tlsperf-backend
      image: tlspack/tlsperf:latest
      imagePullPolicy: Always
      workingDir: /tlsperf_web/server/
      command: ["python3"]
      args: ["main.py"]
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP      
        - name: HOST
          value: "0.0.0.0"
        - name: BPORT
          value: "8887"
        - name: SPORT
          value: "7000"
        - name: STATS_TICKS
          value: "2"
    - name: tlsperf-frontend
      image: tlspack/tlsperf:latest
      imagePullPolicy: Always
      workingDir: /tlsperf_web/ui/
      command: ["/root/.nvm/versions/node/v17.4.0/bin/node"]
      args: ["build"]
      env:
        - name: HOST
          value: "0.0.0.0"
        - name: BPORT
          value: "8887"
        - name: PORT
          value: "8888"
  nodeSelector:
    tgid: Node0


---


apiVersion: v1
kind: Service
metadata:
  name: tlsperf-web-service
spec:
  type: NodePort
  selector:
    app: tlsperf-web
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30007
      name: web
    - protocol: UDP
      port: 7000
      targetPort: 7000
      nodePort: 30008
      name: stats

